site_name: ROBLOX - Error_code wiki
site_url: https://roxyzzsky.github.io/Error-code-wiki/
site_author: Roxyzzstars
site_description: >-
  The official Wiki for the game ERROR_CODE on Roblox. On this page you can find all the information about the game, including guides, tips, and more!
theme:
  name: material
  custom_dir: ./docs/theme_overrides
  font:
    text: Inter
  logo: assets/site_internal/studioinsanity.png
  favicon: assets/site_internal/studioinsanity.png
  icon:
    logo: fontawesome/solid/database
  palette:
    scheme: slate
    primary: custom
  features:
    - content.code.copy
    - navigation.footer
    - navigation.tabs
    - navigation.expand
    - navigation.indexes 
    - toc.integrate
  static_templates:
    - 404.html

##nav:
  ##- Introduction: index.md
not_in_nav: | ## Pages that should be hidden
  page_locked.md
  Roxy.md
  nightmail.md
  nightmare.md
extra_css:
  - stylesheets/extra.css
  - stylesheets/entitythemes.css
  - stylesheets/admonitions.css

extra_javascript:
  - page_js/page_lock.js
  - page_js/theme_switch.js

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2026 | Studio Insanity